name: Build and Release Binaries

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build for Linux
        if: matrix.platform == 'ubuntu-latest'
        run: |
          cargo build --release
          mkdir -p artifacts
          mv target/release/TempVoiceRust artifacts/TempVoiceRust-linux

      - name: Build for Windows
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          cargo build --release
          New-Item -ItemType Directory -Path artifacts -Force
          Move-Item target\release\TempVoiceRust.exe artifacts\TempVoiceRust-windows.exe

      - name: Upload Binaries
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: artifacts/
